# Placement-b

In [1]:
import numpy as np
import pandas as pd 

In [2]:
dataset = pd.read_csv(r"C:\Users\TEMP\Downloads\Placement_Data_Full_Class.csv")

In [3]:
dataset.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [4]:
dataset.isnull().any()

sl_no             False
gender            False
ssc_p             False
ssc_b             False
hsc_p             False
hsc_b             False
hsc_s             False
degree_p          False
degree_t          False
workex            False
etest_p           False
specialisation    False
mba_p             False
status            False
salary             True
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["status"]=le.fit_transform(dataset["status"])

In [6]:
x = dataset.iloc[:,1:13].values
y = dataset.iloc[:,13].values

In [7]:
x

array([['M', 67.0, 'Others', ..., 55.0, 'Mkt&HR', 58.8],
       ['M', 79.33, 'Central', ..., 86.5, 'Mkt&Fin', 66.28],
       ['M', 65.0, 'Central', ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       ['M', 67.0, 'Others', ..., 59.0, 'Mkt&Fin', 69.72],
       ['F', 74.0, 'Others', ..., 70.0, 'Mkt&HR', 60.23],
       ['M', 62.0, 'Central', ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [8]:
dataset.head(3)

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   

    degree_t workex  etest_p specialisation  mba_p  status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80       1  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28       1  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80       1  250000.0

In [9]:
dataset["gender"].unique()

array(['M', 'F'], dtype=object)

In [10]:
dataset["ssc_b"].unique()

array(['Others', 'Central'], dtype=object)

In [11]:
dataset["workex"].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
dataset["hsc_s"].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [14]:
dataset["hsc_b"].unique()

array(['Others', 'Central'], dtype=object)

In [15]:
dataset["degree_t"].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [16]:

dataset["specialisation"].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["gender"] = le.fit_transform(dataset["gender"])
dataset["ssc_b"] = le.fit_transform(dataset["ssc_b"])
dataset["hsc_b"] = le.fit_transform(dataset["hsc_b"])
dataset["hsc_s"] = le.fit_transform(dataset["hsc_s"])
dataset["degree_t"] = le.fit_transform(dataset["degree_t"])
dataset["workex"] = le.fit_transform(dataset["workex"])
dataset["specialisation"] = le.fit_transform(dataset["specialisation"])


In [18]:
dataset

sl_no  gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  \
0        1       1  67.00      1  91.00      1      1     58.00         2   
1        2       1  79.33      0  78.33      1      2     77.48         2   
2        3       1  65.00      0  68.00      0      0     64.00         0   
3        4       1  56.00      0  52.00      0      2     52.00         2   
4        5       1  85.80      0  73.60      0      1     73.30         0   
5        6       1  55.00      1  49.80      1      2     67.25         2   
6        7       0  46.00      1  49.20      1      1     79.00         0   
7        8       1  82.00      0  64.00      0      2     66.00         2   
8        9       1  73.00      0  79.00      0      1     72.00         0   
9       10       1  58.00      0  70.00      0      1     61.00         0   
10      11       1  58.00      0  61.00      0      1     60.00         0   
11      12       1  69.60      0  68.40      0      1     78.30         0   
12      13       0  47.00      0  55.00      1      2     65.00         0   
13      14       0  77.00      0  87.00      0      1     59.00         0   
14      15       1  62.00      0  47.00      0      1     50.00         0   
15      16       0  65.00      0  75.00      0      1     69.00         0   
16      17       1  63.00      0  66.20      0      1     65.60         0   
17      18       0  55.00      0  67.00      0      1     64.00         0   
18      19       0  63.00      0  66.00      0      1     64.00         0   
19      20       1  60.00      1  67.00      1      0     70.00         0   
20      21       1  62.00      1  65.00      1      1     66.00         0   
21      22       0  79.00      1  76.00      1      1     85.00         0   
22      23       0  69.80      1  60.80      1      2     72.23         2   
23      24       0  77.40      1  60.00      1      2     64.74         2   
24      25       1  76.50      1  97.70      1      2     78.86         2   
25      26       0  52.58      1  54.60      0      1     50.20         0   
26      27       1  71.00      1  79.00      1      1     66.00         0   
27      28       1  63.00      1  67.00      1      1     66.00         0   
28      29       1  76.76      1  76.50      1      1     67.50         0   
29      30       1  62.00      0  67.00      0      1     58.00         0   
..     ...     ...    ...    ...    ...    ...    ...       ...       ...   
185    186       0  88.00      0  72.00      0      2     78.00         1   
186    187       0  52.00      0  64.00      0      1     61.00         0   
187    188       1  78.50      0  65.50      0      2     67.00         2   
188    189       1  61.80      1  47.00      1      1     54.38         0   
189    190       0  54.00      0  77.60      1      1     69.20         0   
190    191       0  64.00      1  70.20      0      1     61.00         0   
191    192       1  67.00      1  61.00      0      2     72.00         0   
192    193       1  65.20      0  61.40      0      1     64.80         0   
193    194       0  60.00      0  63.00      0      0     56.00         1   
194    195       1  52.00      1  55.00      1      1     56.30         0   
195    196       1  66.00      0  76.00      0      1     72.00         0   
196    197       1  72.00      1  63.00      1      2     77.50         2   
197    198       0  83.96      1  53.00      1      2     91.00         2   
198    199       0  67.00      0  70.00      0      1     65.00         1   
199    200       1  69.00      1  65.00      1      1     57.00         0   
200    201       1  69.00      1  60.00      1      1     65.00         0   
201    202       1  54.20      0  63.00      1      2     58.00         0   
202    203       1  70.00      0  63.00      0      2     66.00         2   
203    204       1  55.68      1  61.33      1      1     56.87         0   
204    205       0  74.00      1  73.00      1      1     73.00         0   
2

In [21]:
x = dataset.iloc[:,1:13]
y = dataset.iloc[:,13]

In [22]:
x

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0         1  67.00      1  91.00      1      1     58.00         2       0   
1         1  79.33      0  78.33      1      2     77.48         2       1   
2         1  65.00      0  68.00      0      0     64.00         0       0   
3         1  56.00      0  52.00      0      2     52.00         2       0   
4         1  85.80      0  73.60      0      1     73.30         0       0   
5         1  55.00      1  49.80      1      2     67.25         2       1   
6         0  46.00      1  49.20      1      1     79.00         0       0   
7         1  82.00      0  64.00      0      2     66.00         2       1   
8         1  73.00      0  79.00      0      1     72.00         0       0   
9         1  58.00      0  70.00      0      1     61.00         0       0   
10        1  58.00      0  61.00      0      1     60.00         0       1   
11        1  69.60      0  68.40      0      1     78.30         0       1   
12        0  47.00      0  55.00      1      2     65.00         0       0   
13        0  77.00      0  87.00      0      1     59.00         0       0   
14        1  62.00      0  47.00      0      1     50.00         0       0   
15        0  65.00      0  75.00      0      1     69.00         0       1   
16        1  63.00      0  66.20      0      1     65.60         0       1   
17        0  55.00      0  67.00      0      1     64.00         0       0   
18        0  63.00      0  66.00      0      1     64.00         0       0   
19        1  60.00      1  67.00      1      0     70.00         0       1   
20        1  62.00      1  65.00      1      1     66.00         0       0   
21        0  79.00      1  76.00      1      1     85.00         0       0   
22        0  69.80      1  60.80      1      2     72.23         2       0   
23        0  77.40      1  60.00      1      2     64.74         2       1   
24        1  76.50      1  97.70      1      2     78.86         2       0   
25        0  52.58      1  54.60      0      1     50.20         0       1   
26        1  71.00      1  79.00      1      1     66.00         0       1   
27        1  63.00      1  67.00      1      1     66.00         0       0   
28        1  76.76      1  76.50      1      1     67.50         0       1   
29        1  62.00      0  67.00      0      1     58.00         0       0   
..      ...    ...    ...    ...    ...    ...       ...       ...     ...   
185       0  88.00      0  72.00      0      2     78.00         1       0   
186       0  52.00      0  64.00      0      1     61.00         0       0   
187       1  78.50      0  65.50      0      2     67.00         2       1   
188       1  61.80      1  47.00      1      1     54.38         0       0   
189       0  54.00      0  77.60      1      1     69.20         0       0   
190       0  64.00      1  70.20      0      1     61.00         0       0   
191       1  67.00      1  61.00      0      2     72.00         0       0   
192       1  65.20      0  61.40      0      1     64.80         0       1   
193       0  60.00      0  63.00      0      0     56.00         1       1   
194       1  52.00      1  55.00      1      1     56.30         0       0   
195       1  66.00      0  76.00      0      1     72.00         0       1   
196       1  72.00      1  63.00      1      2     77.50         2       1   
197       0  83.96      1  53.00      1      2     91.00         2       0   
198       0  67.00      0  70.00      0      1     65.00         1       0   
199       1  69.00      1  65.00      1      1     57.00         0       0   
200       1  69.00      1  60.00      1      1     65.00         0       0   
201       1  54.20      0  63.00      1      2     58.00         0       0   
202       1  70.00      0  63.00      0      2     66.00         2       0   
203       1  55.68      1  61.33      1      1     56.87         0       0   
204       0  74.00      1  

In [23]:
y

0      1
1      1
2      1
3      0
4      1
5      0
6      0
7      1
8      1
9      0
10     1
11     1
12     0
13     1
14     0
15     1
16     1
17     0
18     0
19     1
20     1
21     1
22     1
23     1
24     1
25     0
26     1
27     1
28     1
29     0
      ..
185    1
186    0
187    1
188    0
189    0
190    0
191    1
192    1
193    1
194    0
195    1
196    1
197    1
198    0
199    1
200    1
201    0
202    1
203    1
204    1
205    1
206    0
207    1
208    0
209    1
210    1
211    1
212    1
213    1
214    0
Name: status, Length: 215, dtype: int32

In [24]:
x = dataset.iloc[:,1:13].values
y = dataset.iloc[:,13].values

In [25]:
x

array([[ 1.  , 67.  ,  1.  , ..., 55.  ,  1.  , 58.8 ],
       [ 1.  , 79.33,  0.  , ..., 86.5 ,  0.  , 66.28],
       [ 1.  , 65.  ,  0.  , ..., 75.  ,  0.  , 57.8 ],
       ...,
       [ 1.  , 67.  ,  1.  , ..., 59.  ,  0.  , 69.72],
       [ 0.  , 74.  ,  1.  , ..., 70.  ,  1.  , 60.23],
       [ 1.  , 62.  ,  0.  , ..., 89.  ,  1.  , 60.22]])

In [26]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [27]:
x.shape

(215, 12)

In [28]:
y.shape

(215,)

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[0,2,4,5,7,8,10])],remainder = "passthrough") 
x = ct.fit_transform(x)

C:\Users\Suprathi\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [30]:
x

array([[ 0.  ,  1.  ,  0.  , ..., 58.  , 55.  , 58.8 ],
       [ 0.  ,  1.  ,  1.  , ..., 77.48, 86.5 , 66.28],
       [ 0.  ,  1.  ,  1.  , ..., 64.  , 75.  , 57.8 ],
       ...,
       [ 0.  ,  1.  ,  0.  , ..., 73.  , 59.  , 69.72],
       [ 1.  ,  0.  ,  0.  , ..., 58.  , 70.  , 60.23],
       [ 0.  ,  1.  ,  1.  , ..., 53.  , 89.  , 60.22]])

In [31]:

x.shape

(215, 21)

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)


In [33]:
x_train.shape

(172, 21)

In [34]:
x_test.shape

(43, 21)

In [35]:
from sklearn.preprocessing import StandardScaler 
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [36]:
x_train

array([[-0.73192505,  0.73192505,  0.90029235, ..., -0.08327934,
        -0.91848631,  0.05194371],
       [ 1.3662601 , -1.3662601 ,  0.90029235, ...,  0.36837381,
        -1.24217438,  0.57709192],
       [ 1.3662601 , -1.3662601 ,  0.90029235, ...,  0.40822555,
         0.58224933,  1.48972813],
       ...,
       [-0.73192505,  0.73192505, -1.1107503 , ...,  0.89973045,
         0.55282314,  0.81842217],
       [-0.73192505,  0.73192505,  0.90029235, ..., -1.22569612,
         0.40569219, -1.30596381],
       [-0.73192505,  0.73192505, -1.1107503 , ..., -1.35853529,
         0.84708503, -1.63056998]])

In [37]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 


In [38]:
ann=Sequential()

In [39]:
ann.add(Dense(21, kernel_initializer = "random_uniform",  activation = "relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [40]:
ann.add(Dense(42, kernel_initializer = "random_uniform",  activation = "relu"))

In [41]:
ann.add(Dense(1, kernel_initializer = "random_uniform",  activation = "sigmoid"))

In [42]:
ann.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [43]:
ann.fit(x_train,y_train,batch_size = 32,epochs = 15)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/15
172/172 [==============================] - 0s 1ms/sample - loss: 0.6924 - acc: 0.6163
Epoch 2/15
172/172 [==============================] - 0s 70us/sample - loss: 0.6895 - acc: 0.7035
Epoch 3/15
172/172 [==============================] - 0s 46us/sample - loss: 0.6856 - acc: 0.7035
Epoch 4/15
172/172 [==============================] - 0s 151us/sample - loss: 0.6799 - acc: 0.7035
Epoch 5/15
172/172 [==============================] - 0s 35us/sample - loss: 0.6716 - acc: 0.7035
Epoch 6/15
172/172 [==============================] - 0s 70us/sample - loss: 0.6586 - acc: 0.7035
Epoch 7/15
172/172 [==============================] - 0s 70us/sample - loss: 0.6396 - acc: 0.7035
Epoch 8/15
172/172 [==============================] - 0s 29us/sample - loss: 0.6171 - acc: 0.7035
Epoch 9/15
172/172 [==============================] - 0s 41us/sample - loss: 0.5865 - acc: 0.7035
Epoch 10/15
172/172 [===

In [44]:
ypred = ann.predict(x_test)

In [45]:
ypred

array([[0.49384877],
       [0.6025793 ],
       [0.8666549 ],
       [0.5249984 ],
       [0.9901768 ],
       [0.6320154 ],
       [0.93025064],
       [0.71296525],
       [0.7968509 ],
       [0.9848194 ],
       [0.5779063 ],
       [0.850399  ],
       [0.90813744],
       [0.603355  ],
       [0.76756537],
       [0.54801995],
       [0.9241768 ],
       [0.48493835],
       [0.8526532 ],
       [0.7709241 ],
       [0.4797511 ],
       [0.5621357 ],
       [0.79510087],
       [0.66189146],
       [0.55181706],
       [0.5777791 ],
       [0.72253305],
       [0.8812455 ],
       [0.7752354 ],
       [0.9456752 ],
       [0.92722356],
       [0.69090974],
       [0.9301545 ],
       [0.6265671 ],
       [0.5635364 ],
       [0.99187905],
       [0.9847364 ],
       [0.7876118 ],
       [0.98239225],
       [0.76825607],
       [0.5695849 ],
       [0.50228226],
       [0.91823655]], dtype=float32)

In [46]:
ypred = ypred>0.5

In [47]:
ypred

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [48]:
y_test

array([0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1])

In [49]:
dataset.head()

sl_no  gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  \
0      1       1  67.00      1  91.00      1      1     58.00         2   
1      2       1  79.33      0  78.33      1      2     77.48         2   
2      3       1  65.00      0  68.00      0      0     64.00         0   
3      4       1  56.00      0  52.00      0      2     52.00         2   
4      5       1  85.80      0  73.60      0      1     73.30         0   

   workex  etest_p  specialisation  mba_p  status    salary  
0       0     55.0               1  58.80       1  270000.0  
1       1     86.5               0  66.28       1  200000.0  
2       0     75.0               0  57.80       1  250000.0  
3       0     66.0               1  59.43       0       NaN  
4       0     96.8               0  55.50       1  425000.0

In [50]:
yp = ann.predict(sc.transform(ct.transform([[1,8.6,0,93.5,1,1,55.9,2,0,54.0,0,56.7]])))

In [51]:
yp

array([[0.48350787]], dtype=float32)

In [52]:
yp>0.5

array([[False]])

# Loanstatus-b

In [53]:
dataset = pd.read_csv(r"C:\Users\Suprathi\Downloads\Telegram Desktop\Loanstatus.csv")

In [54]:
dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes         3+      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No         3+      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No         3+      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes         3+      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [55]:
dataset.isnull().any()

Loan_ID              False
Gender                True
Married               True
Dependents            True
Education            False
Self_Employed         True
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount            True
Loan_Amount_Term      True
Credit_History        True
Property_Area        False
Loan_Status          False
dtype: bool

In [56]:
dataset=dataset.replace(to_replace="3+",value=3)

In [57]:
dataset["Dependents"].unique()

array(['0', '1', '2', 3, nan], dtype=object)

In [58]:

dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes          3      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No          3      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No          3      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes          3      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [59]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)
dataset["Married"].fillna(dataset["Married"].mode()[0],inplace=True)
dataset["Dependents"].fillna(dataset["Dependents"].mode()[0],inplace=True)
dataset["Self_Employed"].fillna(dataset["Self_Employed"].mode()[0],inplace=True)
dataset["LoanAmount"].fillna(dataset["LoanAmount"].mean(),inplace=True)
dataset["Loan_Amount_Term"].fillna(dataset["Loan_Amount_Term"].mean(),inplace=True)
dataset["Credit_History"].fillna(dataset["Credit_History"].mean(),inplace=True)

In [60]:
dataset.isnull().any()

Loan_ID              False
Gender               False
Married              False
Dependents           False
Education            False
Self_Employed        False
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount           False
Loan_Amount_Term     False
Credit_History       False
Property_Area        False
Loan_Status          False
dtype: bool

In [61]:
dataset["Gender"].mode()[0]

'Male'

In [62]:
dataset["Married"].mode()[0]

'Yes'

In [63]:
dataset["Dependents"].mode()[0]

'0'

In [64]:
dataset["Self_Employed"].mode()[0]

'No'

In [65]:
dataset["LoanAmount"].mean()

146.41216216216213

In [66]:
dataset["Loan_Amount_Term"].mean()

342.0

In [67]:
dataset["Credit_History"].mean()

0.8421985815602844

In [68]:
dataset.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [69]:
dataset["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [70]:
dataset["Married"].unique()

array(['No', 'Yes'], dtype=object)

In [71]:
dataset["Education"].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [72]:
dataset["Self_Employed"].unique()

array(['No', 'Yes'], dtype=object)

In [73]:
dataset["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Gender"] = le.fit_transform(dataset["Gender"])
dataset["Married"] = le.fit_transform(dataset["Married"])
dataset["Education"] = le.fit_transform(dataset["Education"])
dataset["Self_Employed"] = le.fit_transform(dataset["Self_Employed"])
dataset["Property_Area"] = le.fit_transform(dataset["Property_Area"])
dataset["Loan_ID"] = le.fit_transform(dataset["Loan_ID"])

In [75]:
dataset.head()

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0        0       1        0          0          0              0   
1        1       1        1          1          0              0   
2        2       1        1          0          0              1   
3        3       1        1          0          1              0   
4        4       1        0          0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Property_Area Loan_Status  
0             1.0              2           Y  
1             1.0              0           N  
2             1.0              2           Y  
3             1.0              2           Y  
4             1.0              2           Y

In [76]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Loan_Status"]=le.fit_transform(dataset["Loan_Status"])

In [77]:
x = dataset.iloc[:,0:12]
y = dataset.iloc[:,12]

In [78]:
x

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0          0       1        0          0          0              0   
1          1       1        1          1          0              0   
2          2       1        1          0          0              1   
3          3       1        1          0          1              0   
4          4       1        0          0          0              0   
5          5       1        1          2          0              1   
6          6       1        1          0          1              0   
7          7       1        1          3          0              0   
8          8       1        1          2          0              0   
9          9       1        1          1          0              0   
10        10       1        1          2          0              0   
11        11       1        1          2          0              0   
12        12       1        1          2          0              0   
13        13       1        0          0          0              0   
14        14       1        1          2          0              0   
15        15       1        0          0          0              0   
16        16       1        0          1          1              0   
17        17       0        0          0          0              0   
18        18       1        1          0          1              0   
19        19       1        1          0          0              0   
20        20       1        1          0          1              0   
21        21       1        1          1          0              0   
22        22       1        1          0          1              0   
23        23       1        1          2          1              0   
24        24       1        1          1          0              0   
25        25       1        1          0          0              1   
26        26       1        1          0          0              0   
27        27       1        1          2          1              0   
28        28       1        0          0          1              0   
29        29       0        0          2          0              0   
..       ...     ...      ...        ...        ...            ...   
584      584       1        1          1          0              0   
585      585       1        1          1          0              0   
586      586       1        1          0          0              0   
587      587       0        0          0          1              0   
588      588       1        0          0          0              0   
589      589       1        1          2          0              1   
590      590       1        1          0          0              0   
591      591       1        1          2          0              1   
592      592       1        0          3          0              1   
593      593       1        1          0          0              0   
594      594       1        1          0          0              1   
595      595       1        0          0          1              0   
596      596       1        1          2          1              1   
597      597       1        0          0          0              0   
598      598       1        1          0          0              1   
599      599       1        1          2          0              0   
600      600       0        0          3          0              0   
601      601       1        1          0          1              0   
602      602       1        1          3          0              0   
603      603       1        0          0          0              0   
604      604       0        1          1          0              0   
605      605       1        1          0          1              0   
606      606       1        1          1          0              0   
607      607       1        1          2          1              0   
608      608       1        1          0          0              0   
609      609   

In [79]:

y

0      1
1      0
2      1
3      1
4      1
5      1
6      1
7      0
8      1
9      0
10     1
11     1
12     1
13     0
14     1
15     1
16     1
17     0
18     0
19     1
20     0
21     1
22     0
23     0
24     0
25     1
26     1
27     1
28     0
29     1
      ..
584    0
585    0
586    1
587    1
588    1
589    0
590    1
591    0
592    1
593    1
594    1
595    1
596    0
597    0
598    1
599    1
600    0
601    1
602    1
603    1
604    1
605    0
606    1
607    1
608    1
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int32

In [80]:
x = dataset.iloc[:,0:12].values
y = dataset.iloc[:,12].values

In [81]:
x

array([[0, 1, 0, ..., 360.0, 1.0, 2],
       [1, 1, 1, ..., 360.0, 1.0, 0],
       [2, 1, 1, ..., 360.0, 1.0, 2],
       ...,
       [611, 1, 1, ..., 360.0, 1.0, 2],
       [612, 1, 1, ..., 360.0, 1.0, 2],
       [613, 0, 0, ..., 360.0, 0.0, 1]], dtype=object)

In [82]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [83]:
x.shape

(614, 12)

In [84]:
y.shape

(614,)

In [85]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[1,2,4,5,11])],remainder = "passthrough") 
x = ct.fit_transform(x)

C:\Users\Suprathi\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [86]:
x

array([[0.0, 1.0, 1.0, ..., 146.41216216216216, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 128.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 66.0, 360.0, 1.0],
       ...,
       [0.0, 1.0, 0.0, ..., 253.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 187.0, 360.0, 1.0],
       [1.0, 0.0, 1.0, ..., 133.0, 360.0, 0.0]], dtype=object)

In [87]:
x.shape

(614, 18)

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)


In [89]:
x_train.shape

(491, 18)

In [90]:
x_test.shape

(123, 18)

In [91]:
from sklearn.preprocessing import StandardScaler 

In [92]:
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [93]:
x_train

array([[-0.47374983,  0.47374983, -0.71143163, ..., -0.18814516,
         0.27644707,  0.45859914],
       [-0.47374983,  0.47374983,  1.40561644, ...,  0.56269516,
         0.27644707,  0.01148007],
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.01977985,
         0.27644707, -2.37482957],
       ...,
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.60890072,
         0.27644707,  0.45859914],
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.14684514,
         0.27644707,  0.45859914],
       [ 2.11081869, -2.11081869, -0.71143163, ...,  0.40097571,
         0.27644707,  0.45859914]])

In [94]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 


In [95]:
ann = Sequential()

In [96]:
ann.add(Dense(18, kernel_initializer = "random_uniform",  activation = "relu"))

In [97]:

ann.add(Dense(36, kernel_initializer = "random_uniform",  activation = "relu"))

In [98]:
ann.add(Dense(1, kernel_initializer = "random_uniform",  activation = "sigmoid"))

In [99]:
ann.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [100]:
ann.fit(x_train,y_train,batch_size = 32,epochs = 25)

Epoch 1/25
491/491 [==============================] - 0s 339us/sample - loss: 0.6910 - acc: 0.6660
Epoch 2/25
491/491 [==============================] - 0s 35us/sample - loss: 0.6856 - acc: 0.6762
Epoch 3/25
491/491 [==============================] - 0s 45us/sample - loss: 0.6753 - acc: 0.6762
Epoch 4/25
491/491 [==============================] - 0s 33us/sample - loss: 0.6546 - acc: 0.6762
Epoch 5/25
491/491 [==============================] - 0s 26us/sample - loss: 0.6217 - acc: 0.6864
Epoch 6/25
491/491 [==============================] - 0s 31us/sample - loss: 0.5757 - acc: 0.7597
Epoch 7/25
491/491 [==============================] - 0s 42us/sample - loss: 0.5299 - acc: 0.7943
Epoch 8/25
491/491 [==============================] - 0s 57us/sample - loss: 0.4986 - acc: 0.8086
Epoch 9/25
491/491 [==============================] - 0s 35us/sample - loss: 0.4773 - acc: 0.8086
Epoch 10/25
491/491 [==============================] - 0s 35us/sample - loss: 0.4643 - acc: 0.8065
Epoch 11/25
491/49

In [101]:
ypred = ann.predict(x_test)

In [102]:
ypred

array([[0.86310744],
       [0.8681727 ],
       [0.751675  ],
       [0.8678475 ],
       [0.9033481 ],
       [0.090767  ],
       [0.8849163 ],
       [0.6466269 ],
       [0.04243782],
       [0.92248964],
       [0.8807043 ],
       [0.93469965],
       [0.7768784 ],
       [0.77546287],
       [0.8636278 ],
       [0.89256716],
       [0.59650457],
       [0.8157667 ],
       [0.7356293 ],
       [0.05228633],
       [0.04209417],
       [0.91655624],
       [0.78301144],
       [0.76512754],
       [0.6685321 ],
       [0.833019  ],
       [0.7296544 ],
       [0.8305521 ],
       [0.03183889],
       [0.05947891],
       [0.73687047],
       [0.560234  ],
       [0.8857447 ],
       [0.6747596 ],
       [0.8716576 ],
       [0.06555372],
       [0.8866231 ],
       [0.6246406 ],
       [0.88596666],
       [0.8775836 ],
       [0.8145629 ],
       [0.04710308],
       [0.91244143],
       [0.7523092 ],
       [0.86579573],
       [0.46956706],
       [0.9069115 ],
       [0.860

In [103]:
ypred = ypred>0.5

In [104]:
ypred

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [105]:
y_test

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1])

In [106]:
dataset.head(3)

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0        0       1        0          0          0              0   
1        1       1        1          1          0              0   
2        2       1        1          0          0              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1

In [107]:
yp = ann.predict(sc.transform(ct.transform([[2,1,0,1,1,0,325,12.7,3986,768.8,1,2]])))

In [108]:
yp

array([[0.8000265]], dtype=float32)

In [109]:
yp>0.5

array([[ True]])

# 50startups-c

In [110]:
dataset=pd.read_csv(r"C:\Users\Suprathi\Downloads\Telegram Desktop\50_startups.csv")

In [111]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [112]:
titles=list(dataset.columns)
titles

['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit']

In [113]:
titles[3],titles[0]=titles[0],titles[3]
titles

['State', 'Administration', 'Marketing Spend', 'R&D Spend', 'Profit']

In [114]:
dataset=dataset[titles]
dataset

State  Administration  Marketing Spend  R&D Spend     Profit
0     New York       136897.80        471784.10  165349.20  192261.83
1   California       151377.59        443898.53  162597.70  191792.06
2      Florida       101145.55        407934.54  153441.51  191050.39
3     New York       118671.85        383199.62  144372.41  182901.99
4      Florida        91391.77        366168.42  142107.34  166187.94
5     New York        99814.71        362861.36  131876.90  156991.12
6   California       147198.87              NaN  134615.46  156122.51
7      Florida       145530.06        323876.68  130298.13  155752.60
8     New York       148718.95        311613.29  120542.52  152211.77
9   California       108679.17        304981.62  123334.88  149759.96
10     Florida             NaN        229160.95  101913.08  146121.95
11  California        91790.61        249744.55  100671.96  144259.40
12     Florida       127320.38        249839.44   93863.75  141585.52
13  California       135495.07        252664.93   91992.39  134307.35
14     Florida       156547.42        256512.92  119943.24  132602.65
15    New York       122616.84        261776.23  114523.61  129917.04
16  California       121597.55        264346.06   78013.11  126992.93
17    New York       145077.58        282574.31   94657.16  125370.37
18     Florida       114175.79        294919.57   91749.16  124266.90
19    New York       153514.11             0.00   86419.70  122776.86
20  California       113867.30        298664.47   76253.86  118474.03
21    New York       153773.43        299737.29   78389.47  111313.02
22     Florida       122782.75        303319.26   73994.56  110352.25
23     Florida       105751.03        304768.73   67532.53  108733.99
24    New York        99281.34        140574.81   77044.01  108552.04
25  California       139553.16        137962.62   64664.71  107404.34
26     Florida       144135.98        134050.07   75328.87  105733.54
27    New York       127864.55        353183.81   72107.60  105008.31
28     Florida       182645.56        118148.20   66051.52  103282.38
29    New York       153032.06        107138.38   65605.48  101004.64
30     Florida       115641.28         91131.24   61994.48   99937.59
31    New York       152701.92         88218.23   61136.38   97483.56
32  California       129219.61         46085.25   63408.86   97427.84
33     Florida       103057.49        214634.81   55493.95   96778.92
34  California       157693.92        210797.67   46426.07   96712.80
35    New York        85047.44        205517.64   46014.02   96479.51
36     Florida       127056.21        201126.82   28663.76   90708.19
37  California        51283.14        197029.42   44069.95   89949.14
38    New York        65947.93        185265.10   20229.59   81229.06
39  California        82982.09        174999.30   38558.51   81005.76
40  California       118546.05        172795.67   28754.33   78239.91
41     Florida        84710.77        164470.71   27892.92   77798.83
42  California        96189.63        148001.11   23640.93   71498.49
43    New York       127382.30         35534.17   15505.73   69758.98
44  California       154806.14         28334.72   22177.74   65200.33
45    New York       124153.04          1903.93    1000.23   64926.08
46     Florida       115816.21        297114.46    1315.46   49490.75
47  California       135426.92             0.00       0.00   42559.73
48    New York        51743.15             0.00     542.05   35673.41
49  California       116983.80         45173.06       0.00   14681.40

In [115]:
dataset.isnull().any()

State              False
Administration      True
Marketing Spend     True
R&D Spend          False
Profit             False
dtype: bool

In [116]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace=True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace=True)

C:\Users\Suprathi\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [117]:
dataset.isnull().any()

State              False
Administration     False
Marketing Spend    False
R&D Spend          False
Profit             False
dtype: bool

In [118]:
dataset

State  Administration  Marketing Spend  R&D Spend     Profit
0     New York   136897.800000    471784.100000  165349.20  192261.83
1   California   151377.590000    443898.530000  162597.70  191792.06
2      Florida   101145.550000    407934.540000  153441.51  191050.39
3     New York   118671.850000    383199.620000  144372.41  182901.99
4      Florida    91391.770000    366168.420000  142107.34  166187.94
5     New York    99814.710000    362861.360000  131876.90  156991.12
6   California   147198.870000    212725.266735  134615.46  156122.51
7      Florida   145530.060000    323876.680000  130298.13  155752.60
8     New York   148718.950000    311613.290000  120542.52  152211.77
9   California   108679.170000    304981.620000  123334.88  149759.96
10     Florida   121564.038163    229160.950000  101913.08  146121.95
11  California    91790.610000    249744.550000  100671.96  144259.40
12     Florida   127320.380000    249839.440000   93863.75  141585.52
13  California   135495.070000    252664.930000   91992.39  134307.35
14     Florida   156547.420000    256512.920000  119943.24  132602.65
15    New York   122616.840000    261776.230000  114523.61  129917.04
16  California   121597.550000    264346.060000   78013.11  126992.93
17    New York   145077.580000    282574.310000   94657.16  125370.37
18     Florida   114175.790000    294919.570000   91749.16  124266.90
19    New York   153514.110000         0.000000   86419.70  122776.86
20  California   113867.300000    298664.470000   76253.86  118474.03
21    New York   153773.430000    299737.290000   78389.47  111313.02
22     Florida   122782.750000    303319.260000   73994.56  110352.25
23     Florida   105751.030000    304768.730000   67532.53  108733.99
24    New York    99281.340000    140574.810000   77044.01  108552.04
25  California   139553.160000    137962.620000   64664.71  107404.34
26     Florida   144135.980000    134050.070000   75328.87  105733.54
27    New York   127864.550000    353183.810000   72107.60  105008.31
28     Florida   182645.560000    118148.200000   66051.52  103282.38
29    New York   153032.060000    107138.380000   65605.48  101004.64
30     Florida   115641.280000     91131.240000   61994.48   99937.59
31    New York   152701.920000     88218.230000   61136.38   97483.56
32  California   129219.610000     46085.250000   63408.86   97427.84
33     Florida   103057.490000    214634.810000   55493.95   96778.92
34  California   157693.920000    210797.670000   46426.07   96712.80
35    New York    85047.440000    205517.640000   46014.02   96479.51
36     Florida   127056.210000    201126.820000   28663.76   90708.19
37  California    51283.140000    197029.420000   44069.95   89949.14
38    New York    65947.930000    185265.100000   20229.59   81229.06
39  California    82982.090000    174999.300000   38558.51   81005.76
40  California   118546.050000    172795.670000   28754.33   78239.91
41     Florida    84710.770000    164470.710000   27892.92   77798.83
42  California    96189.630000    148001.110000   23640.93   71498.49
43    New York   127382.300000     35534.170000   15505.73   69758.98
44  California   154806.140000     28334.720000   22177.74   65200.33
45    New York   124153.040000      1903.930000    1000.23   64926.08
46     Florida   115816.210000    297114.460000    1315.46   49490.75
47  California   135426.920000         0.000000       0.00   42559.73
48    New York    51743.150000         0.000000     542.05   35673.41
49  California   116983.800000     45173.060000       0.00   14681.40

In [119]:
dataset['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [120]:
x=dataset.iloc[:,1:5].values
y=dataset.iloc[:,0:1].values

In [121]:
y

array([['New York'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['California'],
       ['Florida'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['New York'],
       ['Florida'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['Florida'],
       ['New York'],
       ['California'],
       ['Florida'],
       ['California'],
       ['New York'],
       ['Florida'],
       ['California'],
       ['New York'],
       ['California'],
       ['California'],
       ['Florida'],
       ['California'],
       ['New York'],
       ['California'],
       ['New York'],
       ['Florida'],

In [122]:
y.ndim

2

In [123]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [124]:
y

array([[0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0

In [125]:

y.ndim

2

In [126]:
y.shape

(50, 3)

In [127]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [128]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [129]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [130]:
cat=Sequential()

In [131]:
cat.add(Dense(4,kernel_initializer="random_uniform",activation="relu"))

In [132]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

In [133]:
cat.add(Dense(3,kernel_initializer="random_uniform",activation="softmax"))

In [134]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [135]:
cat.fit(x_train,y_train,batch_size=32,epochs=15)

Epoch 1/15
40/40 [==============================] - 0s 3ms/sample - loss: 1.0985 - acc: 0.4000
Epoch 2/15
40/40 [==============================] - 0s 50us/sample - loss: 1.0983 - acc: 0.4000
Epoch 3/15
40/40 [==============================] - 0s 75us/sample - loss: 1.0980 - acc: 0.4000
Epoch 4/15
40/40 [==============================] - 0s 74us/sample - loss: 1.0977 - acc: 0.4000
Epoch 5/15
40/40 [==============================] - 0s 75us/sample - loss: 1.0975 - acc: 0.4000
Epoch 6/15
40/40 [==============================] - 0s 99us/sample - loss: 1.0972 - acc: 0.4000
Epoch 7/15
40/40 [==============================] - 0s 99us/sample - loss: 1.0970 - acc: 0.4000
Epoch 8/15
40/40 [==============================] - 0s 125us/sample - loss: 1.0967 - acc: 0.4000
Epoch 9/15
40/40 [==============================] - 0s 100us/sample - loss: 1.0965 - acc: 0.4000
Epoch 10/15
40/40 [==============================] - 0s 75us/sample - loss: 1.0963 - acc: 0.4000
Epoch 11/15
40/40 [===================

In [136]:
x_train.shape

(40, 4)

In [137]:
y_train.shape

(40, 3)

In [138]:
ypred=cat.predict(x_test)

In [139]:
ypred

array([[0.34188294, 0.32384077, 0.33427632],
       [0.34133494, 0.3246001 , 0.334065  ],
       [0.34135783, 0.32456362, 0.33407852],
       [0.34131798, 0.3246483 , 0.3340338 ],
       [0.34136233, 0.32454035, 0.33409733],
       [0.34126335, 0.32470262, 0.334034  ],
       [0.34132233, 0.3246505 , 0.3340272 ],
       [0.3417495 , 0.32402518, 0.33422533],
       [0.34130418, 0.32464626, 0.33404964],
       [0.34140417, 0.32449484, 0.33410096]], dtype=float32)

In [140]:
ypred[0]

array([0.34188294, 0.32384077, 0.33427632], dtype=float32)

In [141]:
y_test[0]

array([0.0, 1.0, 0.0], dtype=object)

In [142]:
ypred[1]

array([0.34133494, 0.3246001 , 0.334065  ], dtype=float32)

In [143]:
y_test[1]

array([1.0, 0.0, 0.0], dtype=object)

In [144]:
dataset.head()

State  Administration  Marketing Spend  R&D Spend     Profit
0    New York       136897.80        471784.10  165349.20  192261.83
1  California       151377.59        443898.53  162597.70  191792.06
2     Florida       101145.55        407934.54  153441.51  191050.39
3    New York       118671.85        383199.62  144372.41  182901.99
4     Florida        91391.77        366168.42  142107.34  166187.94

In [145]:
cat.predict_classes(sc.transform([[125,345,225,546]]))

array([0], dtype=int64)

# toy dataset-c

In [146]:
dataset=pd.read_csv(r"C:\Users\Suprathi\Downloads\toy-ds\toy_dataset.csv")

In [147]:
dataset

Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
1            2  Dallas    Male   54   45084.0      No
2            3  Dallas    Male   42   52483.0      No
3            4  Dallas    Male   40   40941.0      No
4            5  Dallas    Male   46   50289.0      No
5            6  Dallas  Female   36   50786.0      No
6            7  Dallas  Female   32   33155.0      No
7            8  Dallas    Male   39   30914.0      No
8            9  Dallas    Male   51   68667.0      No
9           10  Dallas  Female   30   50082.0      No
10          11  Dallas  Female   48   41524.0     Yes
11          12  Dallas    Male   47   54777.0      No
12          13  Dallas    Male   46   62749.0      No
13          14  Dallas  Female   42   50894.0      No
14          15  Dallas  Female   61   38429.0      No
15          16  Dallas    Male   43   34074.0      No
16          17  Dallas    Male   27   50398.0      No
17          18  Dallas    Male   38   46373.0     Yes
18          19  Dallas    Male   47   51137.0      No
19          20  Dallas  Female   35   23688.0      No
20          21  Dallas    Male   57   17378.0      No
21          22  Dallas    Male   33   45919.0      No
22          23  Dallas  Female   33   23001.0      No
23          24  Dallas  Female   27   34292.0     Yes
24          25  Dallas    Male   58   55190.0      No
25          26  Dallas    Male   64   26169.0      No
26          27  Dallas    Male   58   57322.0      No
27          28  Dallas    Male   44   61704.0      No
28          29  Dallas    Male   34   53619.0      No
29          30  Dallas    Male   45   47421.0     Yes
...        ...     ...     ...  ...       ...     ...
149970  149971  Austin  Female   63   99950.0      No
149971  149972  Austin  Female   30   76928.0      No
149972  149973  Austin    Male   46   84395.0      No
149973  149974  Austin  Female   52   77272.0      No
149974  149975  Austin  Female   39   90430.0      No
149975  149976  Austin  Female   51   92132.0      No
149976  149977  Austin    Male   49   91519.0      No
149977  149978  Austin    Male   51  107123.0      No
149978  149979  Austin    Male   58  100949.0      No
149979  149980  Austin    Male   43   86737.0      No
149980  149981  Austin  Female   53   89384.0     Yes
149981  149982  Austin    Male   50   77134.0      No
149982  149983  Austin  Female   47   92157.0      No
149983  149984  Austin  Female   25   92482.0      No
149984  149985  Austin    Male   51   99075.0      No
149985  149986  Austin  Female   25   74947.0      No
149986  149987  Austin  Female   63   80381.0      No
149987  149988  Austin  Female   55   62501.0      No
149988  149989  Austin  Female   26   77823.0      No
149989  149990  Austin    Male   52   83688.0      No
149990  149991  Austin  Female   26   82163.0      No
149991  149992  Austin    Male   51   97510.0      No
149992  149993  Austin    Male   37   88408.0      No
149993  149994  Austin    Male   64   89906.0      No
149994  149995  Austin  Female   37  106097.0      No
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[150000 rows x 6 columns]

In [148]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Gender"]=le.fit_transform(dataset["Gender"])

In [149]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Illness"]=le.fit_transform(dataset["Illness"])

In [150]:
dataset.head()

Number    City  Gender  Age   Income  Illness
0       1  Dallas       1   41  40367.0        0
1       2  Dallas       1   54  45084.0        0
2       3  Dallas       1   42  52483.0        0
3       4  Dallas       1   40  40941.0        0
4       5  Dallas       1   46  50289.0        0

In [151]:
titles=list(dataset.columns)
titles

['Number', 'City', 'Gender', 'Age', 'Income', 'Illness']

In [152]:
titles[0],titles[1]=titles[1],titles[0]
titles

['City', 'Number', 'Gender', 'Age', 'Income', 'Illness']

In [153]:
dataset=dataset[titles]
dataset

City  Number  Gender  Age    Income  Illness
0       Dallas       1       1   41   40367.0        0
1       Dallas       2       1   54   45084.0        0
2       Dallas       3       1   42   52483.0        0
3       Dallas       4       1   40   40941.0        0
4       Dallas       5       1   46   50289.0        0
5       Dallas       6       0   36   50786.0        0
6       Dallas       7       0   32   33155.0        0
7       Dallas       8       1   39   30914.0        0
8       Dallas       9       1   51   68667.0        0
9       Dallas      10       0   30   50082.0        0
10      Dallas      11       0   48   41524.0        1
11      Dallas      12       1   47   54777.0        0
12      Dallas      13       1   46   62749.0        0
13      Dallas      14       0   42   50894.0        0
14      Dallas      15       0   61   38429.0        0
15      Dallas      16       1   43   34074.0        0
16      Dallas      17       1   27   50398.0        0
17      Dallas      18       1   38   46373.0        1
18      Dallas      19       1   47   51137.0        0
19      Dallas      20       0   35   23688.0        0
20      Dallas      21       1   57   17378.0        0
21      Dallas      22       1   33   45919.0        0
22      Dallas      23       0   33   23001.0        0
23      Dallas      24       0   27   34292.0        1
24      Dallas      25       1   58   55190.0        0
25      Dallas      26       1   64   26169.0        0
26      Dallas      27       1   58   57322.0        0
27      Dallas      28       1   44   61704.0        0
28      Dallas      29       1   34   53619.0        0
29      Dallas      30       1   45   47421.0        1
...        ...     ...     ...  ...       ...      ...
149970  Austin  149971       0   63   99950.0        0
149971  Austin  149972       0   30   76928.0        0
149972  Austin  149973       1   46   84395.0        0
149973  Austin  149974       0   52   77272.0        0
149974  Austin  149975       0   39   90430.0        0
149975  Austin  149976       0   51   92132.0        0
149976  Austin  149977       1   49   91519.0        0
149977  Austin  149978       1   51  107123.0        0
149978  Austin  149979       1   58  100949.0        0
149979  Austin  149980       1   43   86737.0        0
149980  Austin  149981       0   53   89384.0        1
149981  Austin  149982       1   50   77134.0        0
149982  Austin  149983       0   47   92157.0        0
149983  Austin  149984       0   25   92482.0        0
149984  Austin  149985       1   51   99075.0        0
149985  Austin  149986       0   25   74947.0        0
149986  Austin  149987       0   63   80381.0        0
149987  Austin  149988       0   55   62501.0        0
149988  Austin  149989       0   26   77823.0        0
149989  Austin  149990       1   52   83688.0        0
149990  Austin  149991       0   26   82163.0        0
149991  Austin  149992       1   51   97510.0        0
149992  Austin  149993       1   37   88408.0        0
149993  Austin  149994       1   64   89906.0        0
149994  Austin  149995       0   37  106097.0        0
149995  Austin  149996       1   48   93669.0        0
149996  Austin  149997       1   25   96748.0        0
149997  Austin  149998       1   26  111885.0        0
149998  Austin  149999       1   25  111878.0        0
149999  Austin  150000       0   37   87251.0        0

[150000 rows x 6 columns]

In [154]:
dataset.isnull().any()

City       False
Number     False
Gender     False
Age        False
Income     False
Illness    False
dtype: bool

In [155]:
dataset['City'].unique()

array(['Dallas', 'New York City', 'Los Angeles', 'Mountain View',
       'Boston', 'Washington D.C.', 'San Diego', 'Austin'], dtype=object)

In [156]:
x=dataset.iloc[:,1:6].values
y=dataset.iloc[:,0:1].values

In [157]:
y

array([['Dallas'],
       ['Dallas'],
       ['Dallas'],
       ...,
       ['Austin'],
       ['Austin'],
       ['Austin']], dtype=object)

In [158]:
y.ndim

2

In [159]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [160]:
y

array([[0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [161]:
y.shape

(150000, 8)

In [162]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [163]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [164]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [165]:
cat=Sequential()

In [166]:
cat.add(Dense(5,kernel_initializer="random_uniform",activation="relu"))

In [167]:
cat.add(Dense(10,kernel_initializer="random_uniform",activation="relu"))

In [168]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="softmax"))

In [169]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [170]:
cat.fit(x_train,y_train,batch_size=32,epochs=15)

Epoch 1/15
120000/120000 [==============================] - 2s 19us/sample - loss: 0.8120 - acc: 0.69951s - 
Epoch 2/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.1547 - acc: 0.9631
Epoch 3/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.0776 - acc: 0.9790
Epoch 4/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.0575 - acc: 0.9831
Epoch 5/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.0452 - acc: 0.9873
Epoch 6/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.0353 - acc: 0.9904
Epoch 7/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.0296 - acc: 0.99180s - loss: 0.0300 - acc:
Epoch 8/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.0264 - acc: 0.9925
Epoch 9/15
120000/120000 [==============================] - 2s 17us/sample - loss: 0.0236 - acc: 0.9929
Epoch 10/15
120000/120000 [========

In [171]:
x_train.shape

(120000, 5)

In [172]:
y_train.shape

(120000, 8)

In [173]:
ypred=cat.predict(x_test)

In [174]:
ypred

array([[0.0000000e+00, 0.0000000e+00, 9.9999964e-01, ..., 3.7763795e-07,
        0.0000000e+00, 0.0000000e+00],
       [9.9693584e-01, 9.3734212e-07, 2.3999894e-06, ..., 6.1914220e-06,
        2.8250066e-03, 2.1901788e-04],
       [0.0000000e+00, 0.0000000e+00, 1.2872698e-26, ..., 4.2787471e-09,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [1.2925935e-03, 4.9586619e-05, 8.5862475e-06, ..., 6.4383050e-05,
        9.9752480e-01, 6.3083845e-04],
       [0.0000000e+00, 5.9172227e-09, 5.9316260e-14, ..., 1.7010361e-05,
        7.7412795e-35, 8.6907970e-24],
       [0.0000000e+00, 0.0000000e+00, 4.1793690e-08, ..., 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [175]:
dataset.head()

City  Number  Gender  Age   Income  Illness
0  Dallas       1       1   41  40367.0        0
1  Dallas       2       1   54  45084.0        0
2  Dallas       3       1   42  52483.0        0
3  Dallas       4       1   40  40941.0        0
4  Dallas       5       1   46  50289.0        0

In [176]:
cat.predict_classes(sc.transform([[7,1,24,75898,0]]))

array([2], dtype=int64)